config/routes.rb
PngHivAids::Application.routes.draw do

  match "/401", to: "errors#unauthorized_401"
  match "/404", to: "errors#not_found_404"
  match "/500", to: "errors#error_500"

  namespace :service do
    resource :messagings do
      post 'nuntium'
    end

  end

  namespace :admin do

    resources :lab_test_categories
    resources :regimen_categories
    resources :lab_tests
    resources :regimens

    resources :order_status, only: [:index]

    resources :site_messages do
      collection do
        get 'all'
      end
    end

    resources :import_survs do
      resources :surv_sites
      member do
        get 'download'
        get 'view'
      end
    end

    resources :surv_sites do
      resources :surv_site_commodities
    end

    resources :sms_logs do
      collection do
        get 'monitor'
      end
    end

    resources :shipments do

      resources :site_messages do
        collection do
          get 'shipment_messages'
        end
      end
      resources :sms_logs

      collection do
        get 'download'
        get 'order'
        post 'add_session'
        put 'mark_status'
        delete 'remove_session'
        post 'create_shipment'
      end

      member do
        post 'update_cost'
      end

    end

    resources :orders do
      collection do
        get 'tab_order_line'
        get 'export'
        get 'export_excel'
      end

      member do
        get 'review'
        put 'reject'
        put 'unreject'
      end

      resources :order_lines do
        member do
          put 'reject'
          put 'approve'
        end

        collection do
          put 'approve_all'
        end
      end
    end
    resources :requisition_reports do
      member do
        post 'import'
        get  'download'
      end
    end

    resources :home

    resources :sites do
      resources :requisition_reports
      resources :site_messages
      member do
        get 'users'
      end
    end

    resources :provinces
    resources :commodities do
      collection do
        put :reorder
      end
    end
    resources :public_holidays
    resources :settings
    resources :categories
    resources :commodity_categories do
      collection do
        get 'template'
        put :reorder
      end
    end
    resources :units
    resources :users do
      member do
        put 'reset'
      end

      collection do
        get 'account' # account_admin_users_path /admin/users/account
        get 'new_password'
        put 'change'
        get 'profile'
        put 'update_profile'
      end

    end
    root :to => 'dashboards#index'
  end

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :homes

  root  :to => "homes#index"

end

app/models/regimen_category.rb
# == Schema Information
#
# Table name: regimen_categories
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RegimenCategory < ActiveRecord::Base
  has_many :regimen

  attr_accessible :description, :name
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/admin/regimen_categories_controller.rb
# encoding: utf-8
module Admin
  class RegimenCategoriesController < Controller
    load_and_authorize_resource

    def index
      @categories = RegimenCategory.order('name ASC').paginate(paginate_options)
    end

    def new
      @category = RegimenCategory.new
    end


    def edit
      @category = RegimenCategory.find(params[:id])
    end

    def create
      @category = RegimenCategory.new(params[:regimen_category])

      if @category.save
        redirect_to admin_regimen_categories_path, notice: 'Regimen Category has been created successfully.'
      else
        render action: "new" 
      end
    end

    def update
      @category = RegimenCategory.find(params[:id])

      if @category.update_attributes(params[:regimen_category])
        redirect_to admin_regimen_categories_path, notice: 'Regimen Category has been updated successfully.' 
      else
        render action: "edit" 
      end
    end

    def destroy
      begin
        @category = RegimenCategory.find(params[:id])
        @category.destroy
        redirect_to admin_regimen_categories_path , :notice => 'Regimen Category has been removed'
      rescue ActiveRecord::StatementInvalid => ex
        redirect_to admin_regimen_categories_path , :alert => ex.message
      end
    end

  end
end

app/views/admin/regimen_categories/_form.html.erb
<%= simple_form_for [:admin, @category ] , :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, input_html: {rows: 5, cols: 40} %>
  <div class="form-actions"> 
    <%= button_save ' Save' %>
    <%= link_button_cancel 'Cancel' , admin_regimen_categories_path %>
  </div>
<% end %>

app/views/admin/regimen_categories/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{ 'Regimen Categories' => admin_regimen_categories_path }, 
            { 'Edit Regimen Category' => nil }]   %>
<% end %>

<%= page_header("Edit Regimen Category") %>

<%= render :partial => 'form' %>

app/views/admin/regimen_categories/index.html.erb
<%content_for :breadcrumb do %>
 <%= breadcrumb [ "Regimen Categoies" => nil] %>
<% end %>

<%= page_header t("Regimen Categories"), :left => 6, :right => 6 do %>
  <%=link_button_new "Regimen Category", new_admin_regimen_category_path %>
<%  end %>

<table class="table table-hover ">
  <thead>
    <tr>
      <th class='nth-table'>#</th>
      <th>Name</th>
      <th>Description</th>
      <th  width="60">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= current_entries + index %></td>
        <td><%= link_to category.name, edit_admin_regimen_category_path(category) %></td>
        <td title="<%= category.description%>" class='td-expand'><%= truncate(category.description) %></td>
        <td>
          <%= link_button_delete 'Delete', admin_regimen_category_path(category),
                      :method => :delete,
                      :confirm => 'Are you sure to delete this category ?' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render_paginate_for @categories %>

app/views/admin/regimen_categories/new.html.erb
<%  content_for :breadcrumb do %>
  <%= breadcrumb [ { "Regimen Categories" => admin_regimen_categories_path }, 
             { "New Regimen Category" => nil} ] %>
<% end %>

<%= page_header "New Regimen Category" %>
<%= render :partial => 'form' %>