config/routes.rb
PngHivAids::Application.routes.draw do

  match "/401", to: "errors#unauthorized_401"
  match "/404", to: "errors#not_found_404"
  match "/500", to: "errors#error_500"

  namespace :service do
    resource :messagings do
      post 'nuntium'
    end

  end

  namespace :admin do

    resources :lab_test_categories
    resources :regimen_categories
    resources :lab_tests
    resources :regimens

    resources :order_status, only: [:index]

    resources :site_messages do
      collection do
        get 'all'
      end
    end

    resources :import_survs do
      resources :surv_sites
      member do
        get 'download'
        get 'view'
      end
    end

    resources :surv_sites do
      resources :surv_site_commodities
    end

    resources :sms_logs do
      collection do
        get 'monitor'
      end
    end

    resources :shipments do

      resources :site_messages do
        collection do
          get 'shipment_messages'
        end
      end
      resources :sms_logs

      collection do
        get 'download'
        get 'order'
        post 'add_session'
        put 'mark_status'
        delete 'remove_session'
        post 'create_shipment'
      end

      member do
        post 'update_cost'
      end

    end

    resources :orders do
      collection do
        get 'tab_order_line'
        get 'export'
        get 'export_excel'
      end

      member do
        get 'review'
        put 'reject'
        put 'unreject'
      end

      resources :order_lines do
        member do
          put 'reject'
          put 'approve'
        end

        collection do
          put 'approve_all'
        end
      end
    end
    resources :requisition_reports do
      member do
        post 'import'
        get  'download'
      end
    end

    resources :home

    resources :sites do
      resources :requisition_reports
      resources :site_messages
      member do
        get 'users'
      end
    end

    resources :provinces
    resources :commodities do
      collection do
        put :reorder
      end
    end
    resources :public_holidays
    resources :settings
    resources :categories
    resources :commodity_categories do
      collection do
        get 'template'
        put :reorder
      end
    end
    resources :units
    resources :users do
      member do
        put 'reset'
      end

      collection do
        get 'account' # account_admin_users_path /admin/users/account
        get 'new_password'
        put 'change'
        get 'profile'
        put 'update_profile'
      end

    end
    root :to => 'dashboards#index'
  end

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :homes

  root  :to => "homes#index"

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                    :integer          not null, primary key
#  site_id               :integer
#  is_requisition_form   :boolean
#  user_place_order_id   :integer
#  order_date            :date
#  user_data_entry_id    :integer
#  review_date           :datetime
#  review_user_id        :integer
#  status                :string(15)
#  requisition_report_id :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  date_submittion       :date
#  order_number          :string(10)
#  rejected_at           :datetime
#  unrejected_at         :datetime
#  approved_at           :datetime
#  approved_user_id      :integer
#

class Order < ActiveRecord::Base
  audited
  belongs_to :site, counter_cache: true
  belongs_to :user_place_order, :class_name => 'User'
  belongs_to :user_data_entry , :class_name => 'User'
  belongs_to :review_user , :class_name => 'User'
  belongs_to :approved_user, :class_name => 'User'
  belongs_to :requisition_report , :class_name => 'RequisitionReport'

  has_many :order_lines, :dependent => :destroy
  has_many :shipments, dependent: :destroy

  validates :site, :order_date,:date_submittion,:site_id , :presence => true
  validates :user_place_order, :presence => true, :if =>  Proc.new{|f| f.is_requisition_form }
  validates :user_data_entry,  :presence => true, :unless => Proc.new{|f| f.is_requisition_form }
  # validate  :unique_order_in_month_year

  attr_accessor :survs
  attr_accessible :date_submittion, :is_requisition_form, :order_date, :review_date,
                  :status, :site_id, :order_lines_attributes,:surv_sites, :site,
                  :user_place_order, :user_data_entry, :requisition_report, :order_number


  accepts_nested_attributes_for :order_lines

  ORDER_STATUS_PENDING   = 'Pending'
  ORDER_STATUS_TO_BE_REVIEWED = 'To Be Reviewed'
  ORDER_STATUS_APPROVED = 'Approved'
  ORDER_STATUS_TO_BE_REVISED = 'To Be Revised'
  ORDER_STATUS_REJECTED = "Rejected"


  ORDER_STATUSES = [ ORDER_STATUS_PENDING, ORDER_STATUS_TO_BE_REVIEWED, ORDER_STATUS_APPROVED, ORDER_STATUS_TO_BE_REVISED]

  def rejected?
    self.status == Order::ORDER_STATUS_REJECTED
  end

  def approved?
    self.status == Order::ORDER_STATUS_APPROVED
  end

  def pending?
    self.status == Order::ORDER_STATUS_PENDING
  end

  def to_be_reviewed?
    self.status == Order::ORDER_STATUS_TO_BE_REVIEWED
  end

  def to_be_revised?
    self.status == Order::ORDER_STATUS_TO_BE_REVISED
  end

  def update_approval
    self.status = Order::ORDER_STATUS_APPROVED
    self.approved_at = Time.zone.now
    if self.save
      self.order_lines.update_all(status: OrderLine::STATUS_APPROVED)
      order_sms = OrderSms.new(self)
      order_sms.alert
    end
  end

  def unique_order_in_month_year
    return true if errors.size >0
    order = Order.where(['site_id = :site_id AND MONTH(order_date)= :month AND YEAR(order_date)= :year ',
                   :site_id => self.site.id, :month => self.order_date.month, :year => self.order_date.year
      ]).first

    if(!order.nil? && order.id != self.id)
      date = order.order_date ? order.order_date.strftime(ENV['DATE_FORMAT']) : ''
      errors.add(:site_id, "#{order.site.name} has already had an order on #{date}")
      errors.add(:order_date, "#{order.site.name} has already had an order on #{date}")
    end
  end

  def self.of_status(status)
    where(['status = :status', :status => status])
  end

  def rejectable?
    return false if !approved?
    !shipped?
  end

  def shipped?
    order_lines.where(['shipment_status = ?', true]).first != nil
  end

  def unrejectable?
    return false if !rejected?
    !shipped?
  end

  def self.of_user(user)
    return where("1=1") if user.admin? || user.data_entry? || user.reviewer? || user.data_entry_and_reviewer?
    return where(['site_id = :site_id', {:site_id => user.site.id}]) if user.site?
    return where('status = :status', :status => ORDER_STATUS_APPROVED) if user.ams?
  end

  def self.embed_total_shipped
    shipped = OrderLine.select('order_lines.order_id, count(*) as total_shipped ')
                             .data_filled
                             .where(["order_lines.shipment_status =?", true])
                             .group("order_lines.order_id").to_sql

    orders = self.select("orders.*, shipped.total_shipped").joins("LEFT JOIN (#{shipped}) as shipped ON shipped.order_id = id")
    orders
  end

  def surv_sites
    @survs ||= SurvSite.find_survs(self.site.id, self.order_date)
  end

  def self.create_from_requisition_report requisition_report
    order_line_import = OrderLineImport.new requisition_report.form.current_path

    requisition_report.order_number = order_line_import.order_number.strip
    requisition_report.status = RequisitionReport::IMPORT_STATUS_SUCCESS

    if requisition_report.save
      site =  requisition_report.site
      order = requisition_report.build_order :date_submittion => requisition_report.created_at,
                                            :is_requisition_form => true,
                                            :order_date => Time.zone.now.to_date,
                                            :status  => Order::ORDER_STATUS_PENDING,
                                            :user_place_order => requisition_report.user,
                                            :site => site,
                                            order_number: requisition_report.order_number

      if order.save
        site.inform_new_order
        order_line_import.import_to(order)
        true
      else
        message = order.errors.full_messages.join("<br />")
        raise ActiveRecord::Rollback, message
      end
    else
      false
    end
  end

  def users_from_site
     site = self.site || Site.new
     site.users
  end

  def import_order_lines
    file_name = order.requisition_report.current_path
  end

  def user_type
    return user_place_order.nil? ? 'Data Entry' : 'Site'
  end

  def user
    self.user_place_order || self.user_data_entry
  end

  def self.total_by_status
    orders = select('COUNT(status) AS total, status').group('status').order('total')
    statuses = {}
     orders.each do |order|
       statuses[order.status] = order.total
     end
     statuses
  end

  def self.in_between date_start, date_end
    orders = where("1=1")
    if !date_start.blank? && !date_end.blank?
      date_start = DateTime.strptime(date_start , ENV['DATE_FORMAT'] )
      date_end   = DateTime.strptime(date_end   , ENV['DATE_FORMAT'] )
      orders = orders.where(['order_date BETWEEN ? AND ?', date_start.beginning_of_day, date_end.end_of_day ])
    end
    orders
  end

  def self.approved
    where("orders.status = :status", :status => Order::ORDER_STATUS_APPROVED)
  end

  def update_status_accepted
    accepted = true
    self.order_lines.each do |order_line|
      if order_line.status != OrderLine::STATUS_APPROVED
        accepted = false
        break
      end
    end

    if accepted
      self.status = Order::ORDER_STATUS_APPROVED
    end
  end
end

app/controllers/admin/orders_controller.rb
module Admin
 class OrdersController < Controller
   load_and_authorize_resource

   skip_load_resource :only => [:tab_order_line] # must skip loading resource by cancan
   skip_authorize_resource :only => [:tab_order_line]


   def index
     @date_start = params[:date_start]
     @date_end   = params[:date_end]
     @orders = Order.includes(:site, :user_data_entry, :review_user)

     if current_user.reviewer?
       @orders = @orders.where(['status != ?', Order::ORDER_STATUS_PENDING ])
     elsif current_user.ams?
       @orders = @orders.where(['status = ?', Order::ORDER_STATUS_APPROVED ])
     elsif !params[:type].blank?
       @orders = @orders.of_status(params[:type])
     end

     @orders = @orders.where(["orders.site_id =? ", params[:site_id]]) if params[:site_id].present?
     @orders = @orders.where(["orders.order_number like ? ", "#{params[:order_number]}%" ]) if params[:order_number].present?

     @orders = @orders.of_user(current_user)
                      .in_between(@date_start, @date_end)
                      .embed_total_shipped
                      .order('id desc')

     @orders = @orders.paginate(paginate_options)

   end

   def show
     load_order
   end

   def review
     @type = params[:type] || CommodityCategory::TYPES_DRUG
     load_order
   end

   def reject
    #  order = Order.find(params[:id])
     swicth_order = SwitchOrder.new(@order)

     if(swicth_order.reject)
       redirect_to admin_orders_path, notice: "Order has been rejected"
     else
       redirect_to admin_orders_path, notice: "Failed to reject order #{@order.try(:id)}-#{@order.try(:order_number)} with reason #{swicth_order.error}"
     end
   end

   def unreject
    #  order = Order.find(params[:id])
     swicth_order = SwitchOrder.new(@order)

     if(swicth_order.unreject)
       redirect_to admin_orders_path, notice: "Order has been approved from rejected"
     else
       redirect_to admin_orders_path, notice: "Failed to approved the rejected order #{@order.try(:id)}-#{@order.try(:order_number)} with reason #{swicth_order.error}"
     end
   end

   def create
     @order = Order.new params[:order]
     @order.user_data_entry = current_user
     @order.status = Order::ORDER_STATUS_TO_BE_REVIEWED
     @order.is_requisition_form = false

    if @order.save
      @order.update_approval if current_user.data_entry_and_reviewer?
      redirect_to admin_orders_path, :notice => 'Order has been created'
    else
      errors = {}
      @order.order_lines.each do |order_line|
         if order_line.errors.size > 0
            errors[order_line.errors.full_messages] = order_line.errors.full_messages
         end
      end

      flash.now[:alert] = "Failed to save order with errors: " + errors.values.join("\n")
      render :new
    end
   end

   def tab_order_line
     @site  = Site.find(params[:site_id])
     @order = Order.new(site: @site, order_date: params[:order_date])
     build_commodity_order_line(@order, @site)
     render :layout => false
   end

   def edit
     load_order
     build_commodity_order_line @order, @order.site
   end

   def update
     load_order

     if current_user.data_entry?
       @order.user_data_entry = current_user
       @order.status = Order::ORDER_STATUS_TO_BE_REVIEWED
     elsif current_user.data_entry_and_reviewer?
       @order.approved_user = current_user
     end

     if @order.update_attributes params[:order]
       @order.update_approval if current_user.data_entry_and_reviewer?
       redirect_to admin_orders_path, :notice => 'Order has been updated succesfully'
     else
       errors = {}
       @order.order_lines.each do |order_line|
         if order_line.errors.size > 0
            errors[order_line.errors.full_messages] = order_line.errors.full_messages
         end
       end

       flash.now[:alert] = "Failed to save order with errors: " + errors.values.join("\n")
       render :edit
     end
   end

   def destroy
     Order.transaction do
       @order = Order.find params[:id]
       @order.requisition_report.destroy if @order.requisition_report
     end
     redirect_to admin_orders_path, :notice => 'Order has been deleted succesfully'
   end

   def export_excel
     month = params[:month].to_i + 1
     year = params[:year].to_i

     start_date = Date.new(year, month, 1)
     end_date   = Date.new(year, month, -1)

     orders = Order.includes(:site, order_lines: [ commodity: [:unit] ])
                  .where(['orders.order_date BETWEEN ? AND ? ', start_date, end_date ])
     orders = orders.where(['orders.status = ?', params[:status] ]) if params[:status].present?
     orders = orders.order('sites.name ASC')

     exporter = ExportExcelOrder.new(orders)

     file = "#{Rails.root}/public/data/orders-#{year}-#{month}.xls"
     exporter.save_to_file(file)

     send_file(file,
               type: 'application/xls',
               disposition: 'attachment',
               streaming: true,
               buffer_size: '4096')
   end

   def export
     file =  "#{Rails.root}/public/data/orders.csv"
     Export.order file, params[:type]
     send_file(file ,
              :filename      =>  "orders.csv",
              :type          =>  'text/csv',
              :disposition   =>  'attachment',
              :streaming     =>  true,
              :buffer_size   =>  '4096')
   end

   # don't refer me coz am private
   private

   def load_order
     @order = Order.includes(order_lines: [commodity: :unit])
                   .order('commodities.position, commodities.name')
                   .find(params[:id])
     @order
   end

   def build_commodity_order_line order, site
     existing_commodities = order.order_lines.map do |order_line|
       order_line.commodity
     end

     non_existing_commodities = Commodity.order('commodities.position ,commodities.name')
                                         .includes(:commodity_category)
                                         .all
                                         .select{|commodity| !existing_commodities.include?(commodity) }


     order_line_completer = OrderLineCompleter.new(order)

     non_existing_commodities.each do |commodity|
       order.order_lines.build :commodity => commodity,
                               :pack_size => commodity.pack_size,
                               :arv_type => commodity.commodity_category.com_type,
                               :stock_on_hand => nil,
                               :monthly_use => nil,
                               :skip_bulk_insert => true,
                               :number_of_client => order_line_completer.query_number_of_patient(commodity),
                               :site_id => order.site.id,
                               :suggestion_order => order.site.suggestion_order,
                               :order_frequency => order.site.order_frequency,
                               :test_kit_waste_acceptable => order.site.test_kit_waste_acceptable
     end
   end
  end
end

app/views/admin/orders/_export_dialog.html.erb
<!-- Modal -->
<%= form_tag export_excel_admin_orders_path, id: 'export-order-form', method: :get do |f| %>
  <div id="export-order-dialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel" class='myModalLabel'>Export Requisition and Order</h3>
    </div>

    <div class="modal-body">
      <div id='export-order-message' style='display:none;' class='alert alert-danger' > </div>
      <p>
        Please select <strong> Month </strong> and <strong> Year </strong> to download the requistions and orders
      </p>

      <br/>
      <table class='import-surv-filter'>
        <tr>
          <td>Month</td>
          <td>Year</td>
          <td>Order Status</td>
        </tr>
        <tr>
          <td>
            <%=select_tag :month, options_for_select(ImportSurv.month_list), prompt: 'Select month', style: 'width: 120px;' %>
          </td>

          <td >
            <%=select_tag :year ,options_for_select(2009..2040), prompt: 'Select year', style: 'width: 120px;' %>
          </td>

          <td >
            <%=select_tag :status ,options_for_select(Order::ORDER_STATUSES), prompt: 'All', style: 'width: 120px;' %>
          </td>
        </tr>
      </table>
    </div>
    <br />
    <br />

    <div class="modal-footer">
      <%= link_button_cancel ' Cancel ', "javascript:void()", :'aria-hidden' => true, data: {dismiss: :modal, skip_loading: true}  %>
      <%= link_button_save ' Download now ', 'javascript:void(0)' , id: 'export-order-send' , data: {skip_loading: true} %>
    </div>
  </div>
<% end %>

app/views/admin/orders/_filter_order.html.erb
<div class='filter-box clearfix' >
    <h4> Filter orders </h4>
    <%= form_tag admin_orders_path(request.query_parameters), :method => 'GET', :style => 'display:inline;' do |f| %>
      <table>
        <tr>
          <td valign="top">
            <span> Site </span>
            <%= select_tag :site_id, options_for_select(@orders.map{|order| [order.site.name, order.site.id]}.uniq, params[:id]),
                           :id => :order_site_id , class: 'order-shipment', class: 'input-short ',
                           :prompt => "Select a site" %>
          </td>

          <td valign="top">
            <span style='margin-left: 10px;'> Order No </span>
            <%= text_field_tag :order_number, params[:order_number], placeholder: 'Order Number', class: 'input-short' %>
          </td>

          <td valign="top" style="padding-left: 20px;">
            <%= button_icon 'search', 'Filter' %>
          </td>

        </tr>

      </table>
    <% end %>
  </div>

</div>

app/views/admin/orders/_form.html.erb
<input type="hidden" value='<%= params[:id]%>' id='table-order-order-id' />
<input type="hidden" value='<%= tab_order_line_admin_orders_path() %>' id='table-order-tab-order-id' />

<%= simple_form_for [:admin, @order], :html => { :class => 'form-horizontal', :id => 'form_order' } do |f| %>
  <%= render 'form_top', f: f if @order.new_record? %>
  <div id='order_lines_tab' class="clearfix">
    <%= render 'order_lines', :f => f, :order => @order %>
  </div>
  <div class="form-actions">
    <%= button_save ' Save '%>
    <%= link_button_cancel 'Cancel', admin_orders_path %>
  </div>
<% end %>

app/views/admin/orders/_order_line_detail_row.html.erb
<tr>
  <td ><%=index%></td>
  <td ><%=order_line.id%></td>
  <td class='td-expand no-wrap' title="<%= h order_line.commodity.name %>"> <%= truncate(order_line.commodity.name)%> </td>
  <td><%= order_line.commodity.quantity_per_packg%></td>
  <td><%= order_line.commodity.pack_size%></td>
  <td><%= order_line.commodity.strength_dosage %></td>
  <td><%= order_line.commodity.unit.name %></td>
  <!-- Disable since surv1 and surv2 are out of date -->
  <!-- <td><%= order_line.number_of_client %></td> -->

  <td><%= order_line.stock_on_hand %></td>
  <td><%= order_line.monthly_use %></td>

  <% if !current_user.data_entry? %>
    <td><%= order_line.system_suggestion %> </td>
    <td><%= order_line.quantity_suggested %></td>
  <% end %>

  <td><%= status(order_line.status) %></td>
  <td class="td-expand expand" title="<%= h order_line.user_reviewer_note %>">
    <%= truncate order_line.user_reviewer_note %>
  </td>
  <td class="td-expand expand" title="<%= h order_line.user_data_entry_note %>" class='error-td expand '>
    <%= truncate order_line.user_data_entry_note %>
  </td>
</tr>

app/views/admin/orders/_order_line_row.html.erb
<%
  order_line_record = order_line_form.object
  row_ref = order_line_record.commodity.id
  error_display = ( order_line_record.errors.full_messages.size > 0 ) ? 'visibility:visible' : 'visibility:hidden;'
  styleError = ( order_line_record.errors.full_messages.size > 0 ) ? 'alert-error' : ''
%>
<tr id='tr_<%= row_ref %>'  data-ref="<%= row_ref%>" class='order_line_row <%=styleError%>'>
    <td ><%=index%></td>
    <% if order.persisted? %>
    <td ><%=order_line_record.id%></td>
    <% end %>

    <td class='td-expand expand' title="<%= order_line_record.commodity.name %>" >

      <%= order_line_form.input :id, :as => 'hidden' %>
      <%= order_line_form.input :status, :as => 'hidden', :input_html => {:value =>''} %>
      <%= order_line_form.input :arv_type, :as => 'hidden', :input_html => {
                            :class=>'validate_field',
                            :'data-ref'=> row_ref,
                            :id => "arv_type_#{row_ref}" } %>


      <%= order_line_form.input :commodity_id, :as => 'hidden' %>
      <%= order_line_form.input :site_id, :as => 'hidden', :input_html => {:class=>'site', :id => "site_#{row_ref}"} %>

      <input type='hidden' id='commodity_name_<%=row_ref%>' value="<%= h order_line_record.commodity.name %>" />
      <%= truncate(order_line_record.commodity.name, :length => 20) %>
    </td>
    <td><%= order_line_record.commodity.quantity_per_packg%></td>
    <td><%= order_line_record.commodity.pack_size%></td>
    <td><%=order_line_record.commodity.strength_dosage %></td>
    <td><%= order_line_record.commodity.unit.name %></td>

    <!-- Disable since surv1 and surv2 are out of date -->
    <!--
    <td>
      <%= order_line_record.number_of_client %>
      <div style="display:none;">
        <%= order_line_form.input :number_of_client, :as => :hidden, :input_html => {
                           :class => 'validate_field number_text',
                           :id => "number_of_client_#{row_ref}",
                           :'data-ref' => row_ref } %>
      </div>
    </td>
    -->

    <td >
      <%= order_line_form.input :stock_on_hand, :label=> '&nbsp;',
                            :wrapper_html => {:class => 'inline-div'},
                            :input_html   => {:class => 'validate_field number_text stock_on_hand',
                                              :'data-ref' => row_ref,
                                              :id => "stock_on_hand_#{row_ref}" },
                            :label_html   => {:class => 'none'}  %>
    </td>

    <td >
      <%= order_line_form.input :monthly_use, :label=> '&nbsp;' ,
                            :wrapper_html => {:class => 'inline-div'},
                            :input_html   => {:class => 'validate_field number_text monthly_use',
                                              :'data-ref' => row_ref,
                                              :id => "monthly_use_#{row_ref}"},
                            :label_html   => {:class => 'none'} %>
    </td>

    <% if !current_user.data_entry? %>
    <td >
      <span id='quantity_system_calculation_<%= row_ref %>' >
        <%= order_line_record.system_suggestion  %>
      </span>
    </td>

    <td >
      <%= order_line_form.input :quantity_suggested, :label=> '&nbsp;' ,
          :wrapper_html => {:class => 'inline-div'},
          :input_html   => {:class => 'validate_field number_text', :'data-ref' => row_ref, :id => "quantity_suggested_#{row_ref}" } ,
          :label_html   => {:class => 'none'}
      %>
    </td>

    <% end %>

    <% if order.status == Order::ORDER_STATUS_TO_BE_REVISED %>
      <td><%= status(order_line_record.status) %></td>
      <td class="td-expand expand" title='<%= h order_line_record.user_reviewer_note %>' >
        <%= truncate order_line_record.user_reviewer_note %>
      </td>
    <% end %>

    <td class='error-td expand ' >
      <%= order_line_form.input :user_data_entry_note, :label=> '&nbsp;' , :as => "string",
          :wrapper_html => {:class => 'inline-div'},
          :input_html   => {:class => :validate_field, :'data-ref' => row_ref, :id => "user_data_entry_note_#{row_ref}" , :style => 'width: 180px;'} ,
          :label_html   => {:class => 'none'}
      %>

      <a href="javascript:void(0)" class="order_popover error" id='error_<%= row_ref %>' style='<%= error_display %>'
         data-skip-loading='true' data-ref='<%= row_ref %>' data-html = 'true' data-placement='left'>
           <i class='icon-exclamation-sign'></i>
      </a>

    </td>
</tr>

app/views/admin/orders/_review_table.html.erb
<table class="table  table table-hover table-order-line-form" >
  <caption style="text-align: right; padding-bottom: 10px;">
    <%= link_icon 'eye', "Hide/Show empty rows", "javascript:void(0)",
                   method: :put,
                   class: "btn btn-primary toggle-empty_order-line" %>

    <%= link_to "Approve All #{type}", approve_all_admin_order_order_lines_path(@order, type: type),
                         method: :put,
                         class: "btn btn-primary" %>
  </caption>
  <thead>
    <tr>
      <th> # </th>
      <th> ID </th>
      <th class="expand">Commodity</th>
      <th class="expand">Qty Per Pack</th>
      <th class="expand">Pack Size</th>
      <th class="expand">Strength</th>
      <th class="expand">Unit</th>
      <th class="expand" title="# Of Patient on Drug regiment"># Patient</th>
      <th class="expand" style='width: 65px;' title="Stock on hand" >Stock on hand</th>
      <th class="expand">Monthly use</th>
      <th class="expand" title="System suggestion">System Suggestion</th>
      <th class="expand" title="Quantity Suggested">Qty suggested</th>
      <th class="expand"> Status</th>
      <th class="expand" width="100"> Entry Note</th>
      <th class="expand"> Reviewer Note</th>
      <th class="expand" colspan="2"> Action </th>
    </tr>
  </thead>

  <tbody>
    <% order_lines.each_with_index do |order_line, index| %>
      <tr>
        <td> <%= index+1 %></td>
        <td> <%= order_line.id %></td>
        <td class="expand td-expand" title="<%= h order_line.commodity.name%>">
          <%= truncate(order_line.commodity.name, :length => 20) %> </td>
        <td><%=order_line.commodity.quantity_per_packg%></td>
        <td><%=order_line.commodity.pack_size%></td>
        <td><%=order_line.commodity.strength_dosage%></td>
        <td><%=order_line.commodity.unit.name%></td>
        <td> <%= order_line.number_of_client %></td>
        <td class="stock_on_hand"> <%= order_line.stock_on_hand %> </td>
        <td class="monthly_use"> <%= order_line.monthly_use %></td>
        <td> <%= order_line.system_suggestion %> </td>

        <td> <%= number_field_tag :quantity_suggested, order_line.quantity_suggested,
                      :id => "quantity_suggested_#{order_line.id}",
                      :class => :number_text %>  </td>
        <td> <span id='status_<%=order_line.id%>' ><%= status(order_line.status) %> </span> </td>
        <td class="td-expand expand" title="<%= h(order_line.user_data_entry_note)%>">
          <%= truncate order_line.user_data_entry_note %> </td>
        <td>
          <%= text_field_tag :reviewer_note, order_line.user_reviewer_note, :id => "user_reviewer_note_#{order_line.id}" %>
        </td>

        <td style="width: 240px;" id='<%=order_line.id %>' >
          <%= link_to 'Approve', approve_admin_order_order_line_url(order, order_line),
                      :title => 'Accept',
                      :'data-ref' => order_line.id,
                      :method => :put,
                      :class => 'approved intercept btn btn-primary' %>
                      </td>
        <td>
          <%= link_to 'Reject', reject_admin_order_order_line_url(order, order_line),
                      :title => 'Reject',
                      :'data-ref' => order_line.id,
                      :method => :put,
                      :class => 'rejected intercept btn btn-danger' %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>