config/routes.rb
PngHivAids::Application.routes.draw do

  match "/401", to: "errors#unauthorized_401"
  match "/404", to: "errors#not_found_404"
  match "/500", to: "errors#error_500"

  namespace :service do
    resource :messagings do
      post 'nuntium'
    end

  end

  namespace :admin do

    resources :lab_test_categories
    resources :regimen_categories
    resources :lab_tests
    resources :regimens

    resources :order_status, only: [:index]

    resources :site_messages do
      collection do
        get 'all'
      end
    end

    resources :import_survs do
      resources :surv_sites
      member do
        get 'download'
        get 'view'
      end
    end

    resources :surv_sites do
      resources :surv_site_commodities
    end

    resources :sms_logs do
      collection do
        get 'monitor'
      end
    end

    resources :shipments do

      resources :site_messages do
        collection do
          get 'shipment_messages'
        end
      end
      resources :sms_logs

      collection do
        get 'download'
        get 'order'
        post 'add_session'
        put 'mark_status'
        delete 'remove_session'
        post 'create_shipment'
      end

      member do
        post 'update_cost'
      end

    end

    resources :orders do
      collection do
        get 'tab_order_line'
        get 'export'
        get 'export_excel'
      end

      member do
        get 'review'
        put 'reject'
        put 'unreject'
      end

      resources :order_lines do
        member do
          put 'reject'
          put 'approve'
        end

        collection do
          put 'approve_all'
        end
      end
    end
    resources :requisition_reports do
      member do
        post 'import'
        get  'download'
      end
    end

    resources :home

    resources :sites do
      resources :requisition_reports
      resources :site_messages
      member do
        get 'users'
      end
    end

    resources :provinces
    resources :commodities do
      collection do
        put :reorder
      end
    end
    resources :public_holidays
    resources :settings
    resources :categories
    resources :commodity_categories do
      collection do
        get 'template'
        put :reorder
      end
    end
    resources :units
    resources :users do
      member do
        put 'reset'
      end

      collection do
        get 'account' # account_admin_users_path /admin/users/account
        get 'new_password'
        put 'change'
        get 'profile'
        put 'update_profile'
      end

    end
    root :to => 'dashboards#index'
  end

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :homes

  root  :to => "homes#index"

end

app/models/requisition_report.rb
# == Schema Information
#
# Table name: requisition_reports
#
#  id           :integer          not null, primary key
#  form         :string(255)
#  site_id      :integer
#  user_id      :integer
#  status       :string(255)      default("PENDING")
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  order_number :string(10)
#

class RequisitionReport < ActiveRecord::Base
   attr_accessible :form, :order_number

   belongs_to :site
   belongs_to :user
   has_one :order, :dependent => :destroy


   IMPORT_STATUS_FAILED  = 'Failed'
   IMPORT_STATUS_SUCCESS = 'Success'
   IMPORT_STATUS_PENDING = 'PENDING'

   IMPORT_STATUSES = [ IMPORT_STATUS_PENDING, IMPORT_STATUS_FAILED, IMPORT_STATUS_SUCCESS ]

   validates :form, :presence => true
   validates :order_number, presence: true
   mount_uploader :form, RequisitionReportUploader

   def save_nested_order
      RequisitionReport.transaction do 
        Order.create_from_requisition_report self
      end
      self.errors.size == 0
   end

end

app/controllers/admin/requisition_reports_controller.rb
module Admin
  class RequisitionReportsController < Controller
    before_filter :load_requistion_reports, :only => :index #overide load_resource
    load_and_authorize_resource
    skip_authorize_resource :only => [:download]

    def index
      load_requistion_reports
    end

    def new
      # @requisition_report = RequisitionReport.new
      fill_attribute
    end

    def create
      @requisition_report = RequisitionReport.new params[:requisition_report]
      fill_attribute

      if @requisition_report.save_nested_order
        redirect_to admin_requisition_reports_path, :notice => 'Order has been created successfully'
      else
        flash.now[:alert] = @requisition_report.errors.full_messages.join("<br />")
        render :new
      end
    end

    def download
         @requisition_report = RequisitionReport.find params[:id]
          send_file(@requisition_report.form.current_path , 
                        :filename      =>  File.basename(@requisition_report.form.current_path) ,
                        :type          =>  'application/xls',
                        :disposition   =>  'attachment',
                        :streaming     =>  true,
                        :buffer_size   =>  '4096')
    end

    def destroy
      begin
        @requisition_report = RequisitionReport.find params[:id]
        @requisition_report.destroy
        redirect_to admin_requisition_reports_path, :notice => 'Requistion Form summitted has been deleted'
      rescue Exception => e
        redirect_to admin_requisition_reports_path, :error => e.message
      end
    end

    def fill_attribute
      @requisition_report.site = current_user.site
      @requisition_report.user = current_user
    end

    def import 
      # @requisition_report = RequisitionReport.find params[:id]
      order = @requisition_report.order
      order.destroy if order
      
      if Order.create_from_requisition_report @requisition_report
        redirect_to admin_orders_path, :notice => 'Order has been created successfully'
      else
        redirect_to admin_requisition_reports_path, :error => 'Failed to import'
      end
    end

    def load_requistion_reports
      if current_user.site?
        @requisition_reports = current_user.site.requisition_reports.paginate(paginate_options)
      elsif current_user.admin?
        @requisition_reports = RequisitionReport.paginate(paginate_options)  
      end
    end

  end

end

app/views/admin/requisition_reports/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Requisition Report" => nil}]  %>
<% end %>
<%= page_header("Requisition Report form", :left => 6, :right => 6) do %>
  <% if current_user.site? %>
    <%= link_button_new 'New Requisition Report', new_admin_requisition_report_path, :class => 'btn' %>
  <% end %>
  <%= link_button_download "Download Template", template_admin_commodity_categories_path(:format =>:xls), :class => 'btn btn-primary' %>
<% end %>

<table class="table table-hover ">
  <thead>
    <tr>
      <th class='nth-table'> # </th>
      <th> Order Number </th>
      <th> File </th>
      <th> Site </th>
      <th> User </th>
      <th> Status </th>
      <th align="right"> Created At </th>
    </tr>
  </thead>
  <tbody>
    <% @requisition_reports.each_with_index do |requisition_report, index| %>
      <tr>
        <td><%=current_entries + index %></td>
        <td>
          <%=requisition_report.order_number %>
        </td>
        <td>
          <%=link_to File.basename(requisition_report.form.current_path) , download_admin_requisition_report_path(requisition_report), :data => {:skip_loading => true} %>
        </td>
        <td><%=requisition_report.site.name %></td>
        <td><%=requisition_report.user.display_name %></td>
        <td><%=requisition_report.status %></td>
        <td><%= time_ago_tag(requisition_report.created_at) %></td>

    <%
       confirm_warning = 'The form has already been imported. Are you sure to reimport it ? [Warning] Re impport the form will automatically delete the previouse imported data '
       confirm_import  =  'Are you sure to import the form'
       msg = (requisition_report.status == RequisitionReport::IMPORT_STATUS_SUCCESS) ? confirm_warning  : confirm_import
     %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render_paginate_for @requisition_reports %>

app/views/admin/requisition_reports/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [
       {"New Requisition Form" => false}
    ] %>
<% end %>

<%= page_header 'Requisition Form Submission' %>

<%=simple_form_for [:admin,@requisition_report], :html => {:class => 'form-horizontal' , :multipart => true} do |f|%>
  <%= f.input :form, :as =>:file %>

  <div class="form-actions">
    <%= button_save ' Upload and Save ' %>
    <%= link_button_cancel 'Cancel', admin_requisition_reports_path %>
  </div>
<% end %>