config/routes.rb
PngHivAids::Application.routes.draw do

  match "/401", to: "errors#unauthorized_401"
  match "/404", to: "errors#not_found_404"
  match "/500", to: "errors#error_500"

  namespace :service do
    resource :messagings do
      post 'nuntium'
    end

  end

  namespace :admin do

    resources :lab_test_categories
    resources :regimen_categories
    resources :lab_tests
    resources :regimens

    resources :order_status, only: [:index]

    resources :site_messages do
      collection do
        get 'all'
      end
    end

    resources :import_survs do
      resources :surv_sites
      member do
        get 'download'
        get 'view'
      end
    end

    resources :surv_sites do
      resources :surv_site_commodities
    end

    resources :sms_logs do
      collection do
        get 'monitor'
      end
    end

    resources :shipments do

      resources :site_messages do
        collection do
          get 'shipment_messages'
        end
      end
      resources :sms_logs

      collection do
        get 'download'
        get 'order'
        post 'add_session'
        put 'mark_status'
        delete 'remove_session'
        post 'create_shipment'
      end

      member do
        post 'update_cost'
      end

    end

    resources :orders do
      collection do
        get 'tab_order_line'
        get 'export'
        get 'export_excel'
      end

      member do
        get 'review'
        put 'reject'
        put 'unreject'
      end

      resources :order_lines do
        member do
          put 'reject'
          put 'approve'
        end

        collection do
          put 'approve_all'
        end
      end
    end
    resources :requisition_reports do
      member do
        post 'import'
        get  'download'
      end
    end

    resources :home

    resources :sites do
      resources :requisition_reports
      resources :site_messages
      member do
        get 'users'
      end
    end

    resources :provinces
    resources :commodities do
      collection do
        put :reorder
      end
    end
    resources :public_holidays
    resources :settings
    resources :categories
    resources :commodity_categories do
      collection do
        get 'template'
        put :reorder
      end
    end
    resources :units
    resources :users do
      member do
        put 'reset'
      end

      collection do
        get 'account' # account_admin_users_path /admin/users/account
        get 'new_password'
        put 'change'
        get 'profile'
        put 'update_profile'
      end

    end
    root :to => 'dashboards#index'
  end

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :homes

  root  :to => "homes#index"

end

app/models/import_surv.rb
# == Schema Information
#
# Table name: import_survs
#
#  id         :integer          not null, primary key
#  surv_type  :string(255)
#  form       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  year       :integer
#  month      :integer
#


#when order approve the surv site should not be able to edit
require 'spreadsheet'

class ImportSurv < ActiveRecord::Base

  belongs_to :user
  has_many :surv_sites, :dependent => :destroy
  belongs_to :import_user, :class_name => 'User'

  attr_accessor :invalid_fields
  # validates_format_of :form, :with => %r{\.(xls)$}i, :message => "Only .xls format is excepted"
  # validates :surv_type, :presence  =>  true
  # validates :form, :presence => true  

  attr_accessible :surv_type, :surv_sites_attributes, :year, :month

  #validates_format_of :form, :with => %r{\.(xls)$}i, :message => "Only .xls format is excepted"
  #validates :import_user, :form, :surv_type, :presence   =>  true

  TYPES_SURV1  = 'SURV1'
  TYPES_SURV2  = 'SURV2'

  TYPES = [ TYPES_SURV1,  TYPES_SURV2 ]

  MONTHS = ['January' ,'February','March' ,'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ]

  validates :month, presence: true 
  validates :year, :numericality => { :only_integer => true}
  validate :uniqueness_of_year_month

  #mount_uploader :form, RequisitionReportUploader
  accepts_nested_attributes_for :surv_sites, reject_if: :reject_empty_row

  def reject_empty_row(attributes)
    reject = true
    attributes['surv_site_commodities_attributes'].each do |key, surv_site_commodities_attributes |
      reject = false if !surv_site_commodities_attributes['quantity'].blank?
    end
    return reject
  end

  def self.month_list
    list = []
    ImportSurv::MONTHS.each_with_index do |month, index|
      list << [month, index]
    end
    list
  end

  def uniqueness_of_year_month
    import = ImportSurv.where([ 'month = :month AND year = :year and surv_type = :type', 
                                :month => self.month, :year => self.year, :type => self.surv_type ]).first
    if(!import.nil? && import.id != self.id)
      error_msg = "#{ImportSurv::MONTHS[self.month]}, #{self.year} has already been chosen"
      errors.add(:year, error_msg)
      errors.add(:month, error_msg)
    end

  end

  def self.of_type type
      ImportSurv.where('surv_type = ? ', type)
  end

  def surv_type_display
     ImportSurv::TYPES.each do |type|
       return type[0] if(type[1] == self.surv_type)
     end
  end

  def validate_surv_form 
    file_name = self.form.current_path
    @book = Spreadsheet.open(file_name)
    if self.surv_type == TYPES_SURV1
      invalid_fields = validate_surv1 
    elsif self.surv_type == TYPES_SURV2
      invalid_fields = validate_surv2
    end
    invalid_fields
  end

  def arv_type
    if self.surv_type == ImportSurv::TYPES_SURV2
      return CommodityCategory::TYPES_DRUG
    else
      return CommodityCategory::TYPES_KIT
    end  
  end 

  def validate_field
    errors.add(:surv_type, "can't be blank") if self.surv_type.nil?
  end

  def validate_surv1
    sheet_arv_request = @book.worksheet 0
    total_rows = sheet_arv_request.count
    header_row = sheet_arv_request.row 0
    min_commodity_column = 4
    max_commodity_column = header_row.count
    total_row_data = max_commodity_column - min_commodity_column
    commodity_quantity_index = 4
    @invalid_fields = {}
    arr_commodity = []
    total_row_data.times.each do |k|
      index = min_commodity_column + k
      arr_commodity << header_row[index]
    end
    @invalid_fields[:site] = find_non_exist_sites sheet_arv_request    
    @invalid_fields[:commodity] = find_none_exist_commodities arr_commodity
  end

  def is_form_error?
    return false if @invalid_fields.nil?
    @invalid_fields[:site].size > 0 || @invalid_fields[:commodity].size > 0
  end

  def find_non_exist_sites sheet_arv_request
    total_rows = sheet_arv_request.count
    arr_none_exist_sites = []
    total_rows.times.each do |i|
      if (i>0)
        row = sheet_arv_request.row i
        if !row[0].nil?
          arr_none_exist_sites << row[0] unless _site(row[0])
        end
      end
    end
    return arr_none_exist_sites
  end

  def find_non_exist_sites_in_surv2 sheet_arv_request
    total_rows = sheet_arv_request.count
    arr_none_exist_sites = []
    total_rows.times.each do |i|
      if (i>2)
        row = sheet_arv_request.row i
        if !row[0].nil?
          arr_none_exist_sites << row[0] unless _site(row[0])
        end
      end
    end
    return arr_none_exist_sites.uniq
  end

  def find_none_exist_commodities commodity
    arr_none_exist_commodities = []
    commodity.each do |el|
      arr_none_exist_commodities << el unless _commodity{|commodity| commodity.name == el }
    end
    return arr_none_exist_commodities
  end

  def find_none_exist_commodities_in_surv2 commodity
    arr_none_exist_commodities = []
    commodity.each do |el|
      arr_none_exist_commodities << el unless _commodity{|commodity| commodity.abbreviation == el}
    end
    return arr_none_exist_commodities
  end

  def validate_surv2
    sheet_arv_request = @book.worksheet 0
    total_rows = sheet_arv_request.count
    header_row = sheet_arv_request.row 1
    min_commodity_column = 27
    max_commodity_column = header_row.count
    total_row_data = max_commodity_column - min_commodity_column
    commodity_quantity_index = 27
    @invalid_fields = {}
    arr_commodity = []
    total_row_data.times.each do |k|
      index = min_commodity_column + k
      arr_commodity << header_row[index] unless header_row[index].nil?
    end
    @invalid_fields[:site] = find_non_exist_sites_in_surv2 sheet_arv_request    
    @invalid_fields[:commodity] = find_none_exist_commodities_in_surv2 arr_commodity
  end

  def import
    file_name = self.form.current_path
    @book = Spreadsheet.open(file_name)
    self.surv_type == TYPES_SURV1 ? read_file_surv1 : read_file_surv2
  end

  def read_file_surv2
    sheet_arv_request = @book.worksheet 0
    total_rows = sheet_arv_request.count
    header_row = sheet_arv_request.row 1
    min_commodity_column = 27
    max_commodity_column = header_row.count
    commodity_quantity_index = 27
    arr_commodity = []

    for k in min_commodity_column..max_commodity_column
      arr_commodity << header_row[k]
    end
    

    total_rows.times.each do |i|
      if (i > 2)
        row = sheet_arv_request.row i
        site_name = row[0]
        site = _site(site_name)
        if site
          surv_site = SurvSite.create!(:import_surv_id => self.id, 
                                       :site_id => site.id, 
                                       :month => row[2], 
                                       :year => row[3],
                                       :surv_type => TYPES_SURV2 
                                       )
          surv_site_commodities = []
          for j in 0..arr_commodity.count-1 
            commodity_abbreviation = arr_commodity[j]
            commodity = _commodity{|commodity| commodity.abbreviation == commodity_abbreviation}
            if (commodity)
              quantity = row[commodity_quantity_index + j]
              surv_site_commodities << SurvSiteCommodity.new( :surv_site_id => surv_site.id, 
                                                              :commodity_id => commodity.id, 
                                                              :quantity => quantity)
            end
          end
          if surv_site_commodities.count > 0
            SurvSiteCommodity.import surv_site_commodities 
            SurvSite.reset_counters surv_site.id, :surv_site_commodities
          end

        end
      end
    end
  end

  def read_file_surv1
    sheet_arv_request = @book.worksheet 0
    total_rows = sheet_arv_request.count
    header_row = sheet_arv_request.row 0
    min_commodity_column = 4
    max_commodity_column = header_row.count
    commodity_quantity_index = 4
    arr_commodity = []

    for k in min_commodity_column..max_commodity_column
      arr_commodity << header_row[k]
    end

    total_rows.times.each do |i|
      if (i > 0)
        row = sheet_arv_request.row i
        site_name = row[0]
        site =  _site(site_name)
        if site
          surv_site_commodities = []
          surv_site = SurvSite.create!(:import_surv_id => self.id, 
                                       :site_id => site.id, 
                                       :month => _full_month(row[2]), 
                                       :year => row[3],
                                       :surv_type => TYPES_SURV1 )

          for j in 0..arr_commodity.count-1 
            commodity_name = arr_commodity[j]
            commodity =  _commodity{|commodity| commodity.name == commodity_name  }  
            if (commodity)
              quantity = row[commodity_quantity_index + j]
              surv_site_commodities << SurvSiteCommodity.new(:surv_site_id => surv_site.id, 
                                                             :commodity_id => commodity.id, 
                                                             :quantity => quantity)
            end
          end

          if surv_site_commodities.count > 0
            SurvSiteCommodity.import surv_site_commodities 
            SurvSite.reset_counters surv_site.id, :surv_site_commodities
          end

        end
      end
    end
  end

  private

  def _full_month month
    months = ImportSurv::MONTHS
    months.each do |m|
      return m if m.start_with? month
    end
    raise month + " : is not in the list of supported months(#{months.join(', ')})"
  end

  def _sites
    @sites ||= Site.all
  end

  def _site(name)
    _sites.each do |site|
      return site if site.name == name
    end
    return nil
  end

  def _commodity(&block)
    _commodities.each do |commodity|
      return commodity if block.call(commodity)
    end
    return nil

app/controllers/admin/import_survs_controller.rb
module Admin
  class ImportSurvsController < Controller
    load_and_authorize_resource

    def index
      @type = params[:type] || ImportSurv::TYPES_SURV1
      @import_survs = ImportSurv.of_type(@type).order('year,month').paginate(paginate_options)
    end

    def edit
      load_import_surv
      load_and_prepare_data
    end

    def update
      load_import_surv

      if(@import_surv.update_attributes(params[:import_surv]))
        redirect_to admin_import_survs_path(:type => @import_surv.surv_type), :notice => 'Surv form has been updated successfully'
      else
        load_and_prepare_data
        render :edit
      end
    end

    def new
      type = params[:type] ||  ImportSurv::TYPES_SURV1
      @import_surv = ImportSurv.new(:surv_type => type)

      load_and_prepare_data
    end

    def create
      @import_surv = ImportSurv.new params[:import_surv]
      @import_surv.user = current_user

      if(@import_surv.save)
        redirect_to admin_import_survs_path(:type =>@import_surv.surv_type), :notice => 'Surv site has been created'
      else 
        load_and_prepare_data
        render :new
      end
    end

    def destroy
      begin
        @province = ImportSurv.find(params[:id])
        @province.destroy
        redirect_to admin_import_survs_path(:type => params[:type]), :notice => "Surv site has been removed" 
      rescue Exception => e
        redirect_to admin_import_survs_path(:type => params[:type] ), :error =>  e.message 
      end
    end

    def view
      load_import_surv
      @sites = Site.order('name').all
      load_commodities_from_surv(@import_surv)
    end

    def load_commodities_from_surv
      @commodities = Commodity.includes(:commodity_category, :regimen, :lab_test)
                              .from_type(@import_surv.arv_type)
                              .order('commodities.position, commodities.name')
    end

    def load_import_surv
      @import_surv = ImportSurv.includes(surv_sites: [:site, surv_site_commodities: [ commodity: [:lab_test, :regimen, :commodity_category]]])
                                 .order('commodities.position, commodities.name')
                                 .find(params[:id])
    end

    def load_sites
      @sites = Site.order('name').all
      @sites
    end

    def load_and_prepare_data
      load_sites
      load_commodities_from_surv

      existing_sites = @import_surv.surv_sites.map(&:site_id)


      @sites.each do |site|
        next if existing_sites.include?(site.id)
        surv_site = @import_surv.surv_sites.build(:site => site, :surv_type => @import_surv.surv_type)
        @commodities.each do |commodity|
          surv_site.surv_site_commodities.build(:commodity => commodity, :quantity => '' )
        end
      end
    end

  end

end

app/views/admin/import_survs/_copy.html.erb
<div id="copy_dialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="myModalLabel">Copy from Excel to site: <span id='copy-to-site'>?</span></h4>
  </div>

  <div class="modal-body">
    <div id='shipment_message' style='display:none;' class='alert' > </div>
    <textarea id='copy_source' style='width: 520px; height: 120px;'></textarea>
    <input type='hidden' id='site_to_paste' />
    <input type='hidden' id='commodity_offset' value='0' />
  </div>

  <div class="modal-footer">
    <%= link_button_cancel ' Close ', "javascript:void()", :'aria-hidden' => true, :data=> {'dismiss' => :modal, :skip_loading => true}  %>
    <%= link_button_save ' Paste ', 'javascript:void(0)' , :id => 'btn-copy-to-site', :class =>'btn-primary' , :data => {:skip_loading => true} %>
  </div>
</div>

app/views/admin/import_survs/_form.html.erb
<%=simple_form_for [:admin, @import_surv], :html => { :class => 'form-horizontal', :id => 'form_order' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :surv_type, :as => :hidden %> 
  <%= render 'form_top', f: f  if @import_surv.new_record? %>

  <div class='alert alert-info'>
    <i class='icon-x'></i> Please enter the number of patient in the following form. You can copy from Excel and paste here.
  </div> 

<% 
  category = nil 
  klass = 'default'
  @commodities.each do |commodity|
    if category && category != commodity.commodity_category.id
      klass = ( klass == 'default' ) ? 'switch_color' : 'default'
    end
    category = commodity.commodity_category.id %>


    <% content_for(:commodity_name) do %>
      <th class='header-grid <% klass %>' title='<%= commodity.ref_name %>' >
        <%= h truncate(commodity.ref_name) %>
      </th>
    <% end %>

    <% content_for(:commodity_strength) do %>
      <td class='header-grid <% klass %>' title='<%= commodity.ref_name %>' >
        <%= commodity.strength_dosage %>
      </td>
    <% end %>

<% end %>
<div class='row-fluid clearfix' >
  <div class="form-fixed" style="position:relative;">
    <table class='table table-hover surv-form table-fixed-header' id='tableFixed' >
      <thead class='header' >
        <tr>
          <th class='header-grid' >Site</th>
          <%= yield(:commodity_name) %>
        </tr>

        <tr>
          <td class='header-grid' >Strength</td>
          <%= yield(:commodity_strength) %>
        </tr>
      </thead>

      <tbody>
        <%  @site_list = [] %>
        <%= f.simple_fields_for :surv_sites  do |surv_site_form| %>
            <%
              style = @i == 1 ? 'border-top: 1px solid #ccc;' : ''
              dom_id = surv_site_form.object.site_id 
              @site_list << dom_id
            %>

            <tr id='site_<%= dom_id %>'>
              <td class='header-grid' style='<%= style %>' title="<%= h surv_site_form.object.site.name %>" > 
                <a href='javascript:void(0)' class='btn btn-mini copy-open-dialog' data-skip-loading='true' 
                   data-id='<%=dom_id%>' data-content="<%=surv_site_form.object.site.name%>" style='display:none;' > 
                   <i class='icon-copy'>
                </i> 
                </a>
                <%= surv_site_form.input :id , :as => :hidden %>
                <%= truncate(surv_site_form.object.site.name, :length => 12) %>  
                <%= surv_site_form.input :site_id, :as => :hidden %>
              </td>
              <% 
                @offset = 0 
                @category = nil
                @klass  = 'default'
              %>
              <%= surv_site_form.simple_fields_for :surv_site_commodities do |surv_site_commodity_form| %>
                <% if !@category.nil? && @category != surv_site_commodity_form.object.commodity.commodity_category.id %>
                  <% @klass = (@klass == 'default') ? 'switch_color' : 'default' %>
                <% end %>
                <% @category = surv_site_commodity_form.object.commodity.commodity_category.id %>
                <% error_hl  = (surv_site_commodity_form.object.errors.size >0 ) ? 'background-color: red !important;' : '' %>
                <td  style='<%= style %> <%= error_hl %>'
                     class='<%= @klass%>' 
                     title="<%=h surv_site_commodity_form.object.commodity.commodity_category.name %>" >
                  <%= surv_site_commodity_form.input :id ,:as => :hidden %>
                  <%= surv_site_commodity_form.input :commodity_id, :as => :hidden %>

                  <%= surv_site_commodity_form.input :quantity, :label => false, :as => :text, 
                                                     :input_html => { :class=> "quantity_item number_text quantity_#{dom_id}",
                                                                      :data => { :id => dom_id, :offset => @offset}
                                                      }

                   %>
                </td>
                <% @offset = @offset + 1 %>
              <% end %>
          </tr>
        <% end %>
      </tbody>
     </table>
  </div>
  
  <div class="form-actions">
    <%= button_save  " Save " %> 
    <%= link_button_cancel 'Cancel', admin_import_survs_path(:type => @import_surv.surv_type) %>
  </div>
</div>
<% end %>
<input type='hidden' id='site-list' value='<%=@site_list.join(',')%>' />
<%= render 'copy' %>

app/views/admin/import_survs/_form_top.html.erb
<div class='well'>
  <table class='import-surv-filter'>
    <tr>
        <td>
          <%=f.input :month, :collection => ImportSurv.month_list, 
                     :label_html => { :style=> 'width: 50px;'},
                     :wrapper_html => {:style=> 'margin-left: 70px;'},
                     :include_blank => 'Select month'
           %>
        </td>
        <td >
          <%=f.input :year ,:collection => 2009..2040,:include_blank => 'Select year' %>
        </td>
        <td style='width: 80px; vertical-align: top; padding-left: 15px;'>
          <%= button_save " Save " %>
        </td>
  </table> 
</div>

app/views/admin/import_survs/edit.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Survs" => admin_import_survs_path(:type => params[:type])}, {"Edit" => nil}]  %>
<% end %>  

<%= page_header "Edit #{@import_surv.surv_type}" %>
<%= render 'form' %>

app/views/admin/import_survs/field_error.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Import Surv" => new_admin_import_surv_path()},
                  {"Fields Error" => nil}]  %>
<% end %> 

<% if @import_surv.is_form_error? %>
  <% if !@import_surv.invalid_fields[:site].empty? %>
    <h4> Sites : </h4>
    <ul>
      <% @import_surv.invalid_fields[:site].each do |el| %>
      <li><%= el %></li>
      <% end %>
    </ul>
  <% end %>

  <% if !@import_surv.invalid_fields[:commodity].empty? %>
    <h4> Commodities : </h4>
    <ul>
      <% @import_surv.invalid_fields[:commodity].each do |el| %>
      <li><%= el %></li>
      <% end %>
    </ul>
  <% end %>
  <ul/>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
      new_admin_import_surv_path(), :class => 'btn btn-primary' %>
</div>

app/views/admin/import_survs/import_new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Import Surv" => nil}]  %>
<% end %>  

<%= page_header "Surv Form uploader" %>

<% url = @import_surv.new_record? ? admin_import_survs_path() : admin_import_surv_path(@import_surv) %>
<%= simple_form_for [:admin, @import_surv], :url => url, :html => {:class => 'form-horizontal' , :multipart => true} do |f| %>
  <%= f.error_notification %>
  <%= f.input :surv_type, collection: ImportSurv::TYPES, :include_blank => 'Select Surv Type' %>
  <%= f.input :form, :as =>:file %>
  <div class="form-actions">
    <%= f.button :submit, :value => "Import", :class => 'btn-primary' %>
    <%= link_to 'Cancel', new_admin_import_surv_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/import_survs/index.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Survs" => false}] %>
<% end %>

<ul class="nav nav-tabs">
  <li class="<%= @type == ImportSurv::TYPES_SURV1 ? 'active' : ' ' %>">
    <%= link_to 'Surv1', admin_import_survs_path(:type => ImportSurv::TYPES_SURV1) %>
  </li>

  <li class="<%= @type == ImportSurv::TYPES_SURV2 ? 'active' : ' ' %>" >
    <%= link_to 'Surv2', admin_import_survs_path(:type => ImportSurv::TYPES_SURV2) %></li>
</ul>

<div class='header-in-tab'>
  <%= page_header "List of Survs" do %>
    <% if @type == ImportSurv::TYPES_SURV1  %>
      <%=link_button_new "New Surv1", new_admin_import_surv_path(:type => ImportSurv::TYPES_SURV1) , class: 'btn' %> 
    <% else %>
      <%=link_button_new "New Surv2", new_admin_import_surv_path(:type => ImportSurv::TYPES_SURV2) , class: 'btn' %>  
    <% end %>
  <%end%>
</div>

<table class="table table-hover ">
  <thead>
    <tr>
      <th> # </th>
      <th> ID </th>
      <th> Sumission Date</th>
      <th> Year </th>
      <th> Month </th>
      <th> Type </th>
      <th width="60"> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @import_survs.each_with_index do |import_surv, index| %>
      <tr>
        <td><%= current_entries + index %></td>
        <td><%= link_to import_surv.id,edit_admin_import_surv_path(import_surv, :type => import_surv.surv_type) %></td>
        <td><%= l(import_surv.created_at.to_date) %>
        </td>

        <td><%= import_surv.year %></td>
        <td><%= ImportSurv::MONTHS[import_surv.month] %></td>
        <td><%= import_surv.surv_type %></td>
        <td>
          <%= link_button_delete ' Delete ',admin_import_surv_path(import_surv,
                                 :type => import_surv.surv_type),
                                 :method => :delete,
                                 :confirm => 'Are you sure to delete this import surv ?' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render_paginate_for @import_survs %>

app/views/admin/import_survs/new.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Survs" => admin_import_survs_path(:type => params[:type])}, {"New" => nil}]  %>
<% end %>  

<%= page_header "New #{@import_surv.surv_type}" %>
<%= render 'form' %>

app/views/admin/import_survs/view.html.erb
<% content_for :breadcrumb do %>
  <%= breadcrumb [{"Survs" => admin_import_survs_path(:type => params[:type])}, "Show" => nil]  %>
<% end %>  
<%= page_header "#{@import_surv.surv_type} for #{ImportSurv::MONTHS[@import_surv.month]}, #{@import_surv.year}" %>

<div class='row-fluid form-fixed'  >
  <table class='table table-hover surv-form table-fixed-header ' >
    <thead class='header' >
      <tr >
         <th class='list-no'>#</th>
         <th class='pos-site'>Site</th>
         <% @commodities.each do |commodity| %>
            <th class='expand'><%= commodity.name %></th>
         <% end %>
      </tr>
    </thead>

    <tbody>
      <% @sites.each_with_index do |site, index| %>
        <tr>
            <td class='list-no'> <%= index+1 %> </td>
            <td class='expand' > <%= site.name %> </td>
            <% surv_site = @import_surv.surv_sites.select{|surv_site| surv_site.site == site }.first %>
            <% @commodities.each do |commodity| %>
              <td>
              <% 
                 quantity = ''
                 if surv_site
                   quantity = surv_site.surv_site_commodities.select{|surv_site_commodity| surv_site_commodity.commodity == commodity}.first.try(:quantity)
                 end
              %>
              <%=quantity %>
              </td>
            <% end %>
        </tr>
      <% end %>

    </tbody>
   </table>
</div>
<br />

<div> <%= link_button_cancel  'Back to Survs', admin_import_survs_path, :class => 'btn' %> </div>